### ISSUE TITLE
Incorrect data type argument for BOOLEAN after upgrade from 3.3.0 to 3.4.0

### ISSUE THREAD

**Issue by mrcnpdlk** [skipperbent/pecee-pixie#26]
PHP has probably a [bug](https://bugs.php.net/bug.php?id=38546).
For fix this we have to use `PDO::PARAM_INT` for `boolean` values instead of `PDO::PARAM_BOOL` 

Bad code [here](https://github.com/skipperbent/pecee-pixie/blob/v3-release/src/Pecee/Pixie/QueryBuilder/QueryBuilderHandler.php#L199)

**Comment by skipperbent** [comment]
Thanks!

Insane that a bug created almost 10 years ago can still lurk around in PHP 😃

**Comment by skipperbent** [comment]
@mrcnpdlk 

Your PR has been added to version 3.4.2.

Thanks for helping out, I really appreciate your hard work 👍 

/ Simon

**Comment by mrcnpdlk** [comment]
Why do You remove `\` from native classes - for example 'PDO'?
I think, that is safer to use them with backslash.

**Comment by mrcnpdlk** [comment]
3.4.2 works. You can close the issue.

**Comment by skipperbent** [comment]
I only did that because `QueryBuilderHandler` already had the `PDO` class imported (`use PDO;`) in the top of the class.

**Comment by skipperbent** [comment]
And you can gain extra speed by performing optcode optimisations on navtive function calls in PHP 7. Using (`\in_array(...)` instead of `in_array(...)`) will cost one less call when compiled (see: https://github.com/Roave/FunctionFQNReplacer)

You can add the `PHP Inspections` plugin to PHPStorm if you want to get tips on how to optimize the code in your projects - it's a great plugin.

**Comment by mrcnpdlk** [comment]
I didnt know. 
Plugin installed, thanks.

**Comment by skipperbent** [comment]
It's a great plugin, I've learned a lot of optimisation-tricks by using it. However some of the inspections can be a little annoying like the "method contains too many properties" etc, but you can always disable those.

**Comment by mrcnpdlk** [comment]
I dont that was a good idea to install it. My source code is blinking now 😄

**Comment by skipperbent** [comment]
Hehehe - yeah it can be really overwhelming if you haven't used it before because it's so strict 😆 

Version 4 will be available in a couple of days or so, as it will give me some time to do a more in-depth code-review, add some missing unit-tests (like the subqueries etc) and optimise the code even more for PHP7.

**Comment by mrcnpdlk** [comment]
Thanks for info. I will be waiting.
