### ISSUE TITLE
Table aliasing ['as' statement]

### ISSUE THREAD

**Issue by mrcnpdlk** [skipperbent/pecee-pixie#4]
In original pixie library I was using something like this for aliasing table:
```
$qb->table(['my_table'=>'foo'])
    ->join('another_table', 'another_table.person_id', '=', 'foo.id')
```
Now, it generates the exception:
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'DATABASE.foo' doesn't exist
```

I found this solution, it works for me:
```
$qb->table($oQueryX->raw('my_table as foo'))
    ->join('another_table', 'another_table.person_id', '=', 'foo.id')
```

Is any easier way?

**Comment by skipperbent** [comment]
Thanks for your feedback.

This issue has been resolved in version 3.1.0.

Alternatively you can use the `prefix` method to change the alias off the class on-the-fly. Please note that this method is deprecated in version 3.1.0 as it has been renamed to `alias`.

Your code above should work; however if you need to change the alias on the fly - or want some easier to understand code, you can use the following method instead:

```
$qb->table('my_table')
    ->alias('my_table', 'foo')
    ->join('another_table', 'another_table.person_id', '=', 'foo.id')
```

In versions below `3.1.0` you have to use the `prefix` instead of `alias`.

Hope it works out - otherwise let me know.

/ Simon

**Comment by skipperbent** [comment]
Oh yeah - by the way I also updated the documentation to better reflect this change.

For anyone looking for examples etc, please refer to:
https://github.com/skipperbent/pecee-pixie#table-alias

**Comment by mrcnpdlk** [comment]
Thanks a lot! I gonna test.
