### ISSUE TITLE
Exception for calling count() on sub-queried query

### ISSUE THREAD

**Issue by mrcnpdlk** [skipperbent/pecee-pixie#88]
If we call count() method for sub-queried query library is throwing the exception.
Use case:
```
$subquery = $oQuery
        ->newQuery()
        ->table('foo_table')
    ;
$oCall = $oQuery->newQuery()->table($oQuery->subQuery($subquery,'q1'));
print_r($oCall->count());
```
Generated query:
```
SELECT COUNT(*) AS `field` FROM (SELECT * FROM (SELECT * FROM `foo_table`) AS `q1`) AS `(SELECT * FROM `foo_table`) AS `q1`_count` LIMIT 1
```

For typical (without sub-query) request the response is OK.

In my opinion the problem is in [aggregate() method](https://github.com/skipperbent/pecee-pixie/blob/4.9.0/src/Pecee/Pixie/QueryBuilder/QueryBuilderHandler.php#L174)

**Comment by skipperbent** [comment]
Hi @mrcnpdlk 

In latest version (4.9.0) your example works fine. 

```php
$subquery = $this->builder
            ->newQuery()
            ->table('foo_table');
        $oCall = $this->builder->newQuery()->table($this->builder->subQuery($subquery,'q1'));
```

Generates the following output:

```sql
SELECT * FROM (SELECT * FROM `cb_foo_table`) AS `q1`
```

Which version are you using?

/ Simon

**Comment by mrcnpdlk** [comment]
Hi @skipperbent
I am using the newest.

Try now call the count () method on it. You will see.

**Comment by skipperbent** [comment]
@mrcnpdlk 

Holy hell - yeah, you're right. It's broken and worst of all tests using the "aggregate" functionality can't be trusted as they don't represent the "real" query because a new one is build when calling the method. Have to find a workaround for that as the connection in the unit-tests are just mockups.

But I've fixed the count-bug. It was because `getTable` returns a string and since the table in our case isn't a string but a Raw-object it returned the entire query and used that as alias in the aggregate method, causing the library to bug-out.

I'll add a release shortly.

/ Simon

**Comment by skipperbent** [comment]
Version 4.9.1 is up - should work again. Guess you were forced to upgrade to php 7.1 after all 😄

**Comment by mrcnpdlk** [comment]
Yes. Because of you I upgraded my environment 😀 to 7.2 version. I'm using https://deb.sury.org packages + pecl for extensions.

**Comment by skipperbent** [comment]
You only had to upgrade to 7.1 - well at least you've saved yourself some future headache hehe 😄 

Thanks for reporting the bug by the way :)

**Comment by mrcnpdlk** [comment]
Issue solved.
